---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  version: 7.7.11
  targetNamespace: argo-cd
  valuesContent: |-
    # удаление crds при удалении helm чарта argoCD
    crds:
      keep: false

    # формат и уровень логов 
    global:
      logging:
        format: json
        # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
        level: info

    controller:
      replicas: 1

    configs:
      params:
        server.insecure: true

      # В последней версии (2.13.1) исправили добавление сертификатов СА
      # tls:
      #   certificates:
      #     myserver-ca: |
      #       -----BEGIN CERTIFICATE-----
      #       ...
      #       -----END CERTIFICATE-----

      
      repositories:
        artur-repo:
          url: https://github.com/vard0ni/k3s-homelab
          name: vard0ni
          type: git

      secret:
        # -- Bcrypt hashed admin password
        ## Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
        ## `htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'`
        argocdServerAdminPassword: "$2a$10$0.dkTxZh5w0dl4wCzW7mmuKebO0kIOSn5uErg8mj4MVYnj8OhAY5O"

    ## Redis
    redis:
      enabled: true

    ## Server
    server:
      name: server
      replicas: 1
      certificate:
        enabled: true
        domain: cluster.local
        renewBefore: 360h
        duration: 9125h
        issuer:
          group: cert-manager.io
          kind: ClusterIssuer
          name: dev-ca-issuer
        privateKey:
          algorithm: RSA
          encoding: PKCS8
          size: 4096
          rotationPolicy: Always
        usages:
          - server auth

      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        ingressClassName: "system-ingress"
        hostname: cluster.local
        path: /
        pathType: Prefix
        tls: true
    
    # В последней версии (2.13.1) исправили добавление сертификатов СА
    # Смотрите выше пример configs.tls.certificates
    repoServer:
      volumes:
      - name: dev-ca-certs
        secret:
          secretName: dev-ca-certs
      volumeMounts:
      - mountPath: /etc/ssl/certs/dev-ca.pem
        name: dev-ca-certs
        subPath: dev-ca.pem
